version: "3.9"
services:
  chatbot-backend:
    image: owenchoh/projects:chatbot-backend-latest
    build: 
      context: ./chatbot-backend
    secrets:
      - gemini_api_key
    environment:
      GEMINI_API_KEY: /run/secrets/gemini_api_key
    volumes:
      - backend-data:/app/database_files
      - backend-uploads:/app/database_files/uploads
    networks:
      - caddy_network

  chatbot-frontend:
    image: owenchoh/projects:chatbot-app-latest
    build: 
      context: ./chatbot-app
    depends_on:
      - chatbot-backend
    networks:
      - caddy_network

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - chatbot-frontend
      - chatbot-backend
    networks:
     - caddy_network

networks:
  caddy_network:
    driver: bridge  # Changed from overlay to bridge

secrets:
  gemini_api_key:
    file: ./secrets/gemini_api_key.txt

volumes:
  backend-data:
  backend-uploads:
  caddy_data:
  caddy_config:
