name: Deploy Application

on:
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: ec2

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker compose -f docker-compose.yaml build

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker compose -f docker-compose.yaml push

  deploy:
    runs-on: ubuntu-latest
    environment: ec2
    
    steps:
    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        scp -i private_key docker-compose.yml $SERVER_USER@$SERVER_HOST:~/app/SC4052-Cloud-Computing-Project
        ssh -i private_key $SERVER_USER@$SERVER_HOST << EOF
          cd ~/app/SC4052-Cloud-Computing-Project
          docker-compose pull
          docker-compose up -d
        EOF
